name: Notify CSK Projects

on:
  push:
    branches:
      - main
    paths:
      - 'css/**'
      - 'fonts/**'
      - 'img/**'
      - 'js/**'
      - 'index.html'
      - 'version'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify projects of common update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CSK_PAT }}
          repository: ianhubnet/csk-projects
          event-type: common-update
