name: Notify CSK Projects

on:
  push:
    branches:
      - main
    paths:
      - 'css/**'
      - 'fonts/**'
      - 'img/**'
      - 'js/**'
      - 'index.html'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify projects of common update
        uses: ianhubnet/github-actions/notify-projects@main
        with:
          token: ${{ secrets.CSK_PAT }}
          event: common-update
